### Read csv option chain table NSE

In [3]:
import pandas as pd
url='./tatasteeloc.csv'
rawData=pd.read_csv(url, header=1)

In [2]:
rawData.info()

NameError: name 'rawData' is not defined

In [48]:
rawData.columns

Index(['Chart', 'OI', 'Chng_in_OI', 'Volume', 'IV', 'LTP', 'Net_Chng',
       'BidQty', 'BidPrice', 'AskPrice', 'AskQty', 'Strike_Price', 'BidQty.1',
       'BidPrice.1', 'AskPrice.1', 'AskQty.1', 'Net_Chng.1', 'LTP.1', 'IV.1',
       'Volume.1', 'Chng_in_OI.1', 'OI.1', 'Chart.1'],
      dtype='object')

In [49]:
rawData.columns=rawData.columns.str.replace(' ','_')

In [50]:
rawData.head(3)

,Chart,OI,Chng_in_OI,Volume,IV,LTP,Net_Chng,BidQty,BidPrice,AskPrice,...,BidPrice.1,AskPrice.1,AskQty.1,Net_Chng.1,LTP.1,IV.1,Volume.1,Chng_in_OI.1,OI.1,Chart.1
0,https://www1.nseindia.com/live_market/resource...,-,-,-,-,-,-,9000,87.30,92.70,...,0.10,0.20,1500,-,0.10,174.92,54,-69000,202500,https://www1.nseindia.com/live_market/resource...
1,https://www1.nseindia.com/live_market/resource...,-,-,-,-,-,-,9000,77.40,84.25,...,-,0.55,1500,-,0.20,-,-,-,16500,https://www1.nseindia.com/live_market/resource...
2,https://www1.nseindia.com/live_market/resource...,1500,-,-,-,88.00,-,9000,66.65,74.25,...,0.15,0.20,6000,-0.25,0.15,159.53,36,-21000,462000,https://www1.nseindia.com/live_market/resource...

In [51]:
rawData.replace(',','', regex=True, inplace=True)
df=rawData.apply(pd.to_numeric,errors='coerce')
df.dropna(axis=1, how='all', inplace=True)

In [52]:
df.head()

,OI,Chng_in_OI,Volume,IV,LTP,Net_Chng,BidQty,BidPrice,AskPrice,AskQty,...,BidQty.1,BidPrice.1,AskPrice.1,AskQty.1,Net_Chng.1,LTP.1,IV.1,Volume.1,Chng_in_OI.1,OI.1
0,NaN,NaN,NaN,NaN,NaN,NaN,9000.0,87.30,92.70,9000.0,...,3000.0,0.10,0.20,1500.0,NaN,0.10,174.92,54.0,-69000.0,202500.0
1,NaN,NaN,NaN,NaN,NaN,NaN,9000.0,77.40,84.25,15000.0,...,NaN,NaN,0.55,1500.0,NaN,0.20,NaN,NaN,NaN,16500.0
2,1500.0,NaN,NaN,NaN,88.0,NaN,9000.0,66.65,74.25,15000.0,...,19500.0,0.15,0.20,6000.0,-0.25,0.15,159.53,36.0,-21000.0,462000.0
3,NaN,NaN,NaN,NaN,NaN,NaN,18000.0,57.60,62.80,18000.0,...,1500.0,0.20,0.35,3000.0,-0.15,0.30,137.20,6.0,NaN,121500.0
4,NaN,NaN,NaN,NaN,NaN,NaN,18000.0,47.90,53.50,18000.0,...,1500.0,0.20,0.30,4500.0,-0.50,0.20,126.68,46.0,-45000.0,316500.0

In [55]:
df.OI=((df.OI/df.OI.sum())*100).round(2)
pd.set_option('display.max_columns', None)
#movies.head()
df

,OI,Chng_in_OI,Volume,IV,LTP,Net_Chng,BidQty,BidPrice,AskPrice,AskQty,Strike_Price,BidQty.1,BidPrice.1,AskPrice.1,AskQty.1,Net_Chng.1,LTP.1,IV.1,Volume.1,Chng_in_OI.1,OI.1
0,NaN,NaN,NaN,NaN,NaN,NaN,9000.0,87.30,92.70,9000.0,180.0,3000.0,0.10,0.20,1500.0,NaN,0.10,174.92,54.0,-69000.0,202500.0
1,NaN,NaN,NaN,NaN,NaN,NaN,9000.0,77.40,84.25,15000.0,190.0,NaN,NaN,0.55,1500.0,NaN,0.20,NaN,NaN,NaN,16500.0
2,0.01,NaN,NaN,NaN,88.00,NaN,9000.0,66.65,74.25,15000.0,200.0,19500.0,0.15,0.20,6000.0,-0.25,0.15,159.53,36.0,-21000.0,462000.0
3,NaN,NaN,NaN,NaN,NaN,NaN,18000.0,57.60,62.80,18000.0,210.0,1500.0,0.20,0.35,3000.0,-0.15,0.30,137.20,6.0,NaN,121500.0
4,NaN,NaN,NaN,NaN,NaN,NaN,18000.0,47.90,53.50,18000.0,220.0,1500.0,0.20,0.30,4500.0,-0.50,0.20,126.68,46.0,-45000.0,316500.0
5,0.03,NaN,NaN,NaN,49.00,NaN,27000.0,36.50,43.35,12000.0,230.0,1500.0,0.30,0.40,1500.0,-0.70,0.35,104.08,129.0,-31500.0,274500.0
6,0.03,-3000.0,3.0,109.91,33.40,1.30,15000.0,28.25,33.15,10500.0,240.0,7500.0,0.65,0.70,22500.0,-1.30,0.65,96.42,380.0,-54000.0,337500.0
7,0.56,-13500.0,27.0,NaN,21.40,1.20,1500.0,21.55,22.05,1500.0,250.0,1500.0,1.50,1.60,19500.0,-2.05,1.50,91.17,763.0,-124500.0,601500.0
8,1.26,-72000.0,163.0,74.15,14.00,1.35,6000.0,13.25,14.00,1500.0,260.0,4500.0,3.40,3.50,16500.0,-3.30,3.35,85.14,1009.0,-181500.0,646500.0
9,3.06,-129000.0,1510.0,74.15,7.60,0.05,1500.0,7.30,7.70,1500.0,270.0,1500.0,6.05,7.10,3000.0,-4.60,7.10,86.19,1290.0,-159000.0,405000.0
10,7.74,-129000.0,2253.0,77.05,3.75,-0.55,1500.0,3.70,3.85,7500.0,280.0,7500.0,12.90,13.55,1500.0,-5.20,13.30,96.12,121.0,-39000.0,235500.0
11,4.16,-84000.0,1249.0,81.57,1.85,-0.75,1500.0,1.70,1.95,4500.0,290.0,3000.0,19.95,22.05,3000.0,-5.80,21.35,68.42,17.0,-15000.0,154500.0
12,12.40,-303000.0,1520.0,89.50,1.00,-0.70,9000.0,1.00,1.05,3000.0,300.0,1500.0,29.90,31.35,1500.0,-6.10,30.20,102.17,24.0,-18000.0,120000.0
13,3.41,-24000.0,405.0,93.04,0.60,-0.40,1500.0,0.55,0.60,9000.0,310.0,7500.0,37.40,42.40,4500.0,NaN,31.15,NaN,NaN,NaN,13500.0
14,4.27,-237000.0,424.0,100.21,0.35,-0.35,1500.0,0.30,0.35,6000.0,320.0,7500.0,49.35,55.30,34500.0,1.75,47.00,NaN,2.0,-1500.0,18000.0
15,2.97,-49500.0,129.0,106.61,0.20,-0.30,1500.0,0.15,0.25,10500.0,330.0,6000.0,56.05,66.15,34500.0,-1.55,56.50,NaN,5.0,-3000.0,9000.0
16,1.71,-30000.0,97.0,111.55,0.10,-0.30,1500.0,0.10,0.15,1500.0,340.0,6000.0,66.70,75.25,3000.0,7.20,67.00,NaN,2.0,-1500.0,4500.0
17,2.79,-78000.0,93.0,117.45,0.10,-0.15,127500.0,0.05,0.10,36000.0,350.0,9000.0,76.65,85.70,3000.0,-0.90,78.00,132.02,2.0,-3000.0,18000.0
18,1.45,-43500.0,60.0,118.86,0.05,-0.15,NaN,NaN,0.05,18000.0,360.0,9000.0,86.75,92.55,9000.0,NaN,95.80,NaN,NaN,NaN,21000.0
19,0.56,-6000.0,4.0,129.02,0.05,-0.05,NaN,NaN,0.20,1500.0,370.0,9000.0,96.85,102.55,9000.0,NaN,83.00,NaN,NaN,NaN,19500.0
20,0.58,-7500.0,7.0,157.47,0.15,NaN,1500.0,0.05,0.15,15000.0,380.0,12000.0,106.90,111.15,6000.0,NaN,97.30,NaN,NaN,NaN,6000.0
21,0.10,-3000.0,2.0,159.91,0.10,NaN,NaN,NaN,0.40,1500.0,390.0,15000.0,115.75,121.00,6000.0,-6.80,118.20,196.77,2.0,-3000.0,4500.0
22,2.00,-108000.0,179.0,157.38,0.05,-0.05,NaN,NaN,0.05,7500.0,400.0,16500.0,127.00,133.10,15000.0,NaN,115.05,NaN,NaN,NaN,27000.0
23,0.04,NaN,NaN,NaN,0.15,NaN,NaN,NaN,0.60,6000.0,410.0,15000.0,136.60,143.05,3000.0,-7.50,137.50,NaN,1.0,NaN,1500.0
24,0.10,NaN,NaN,NaN,0.10,NaN,NaN,NaN,0.05,3000.0,420.0,18000.0,145.55,153.10,15000.0,NaN,135.00,NaN,NaN,NaN,6000.0
25,0.05,NaN,NaN,NaN,7.20,NaN,NaN,NaN,NaN,NaN,430.0,15000.0,156.95,163.10,15000.0,NaN,156.00,NaN,NaN,NaN,1500.0
26,0.03,NaN,NaN,NaN,2.00,NaN,NaN,NaN,0.80,6000.0,440.0,16500.0,167.10,173.10,3000.0,14.00,167.00,NaN,1.0,-1500.0,13500.0
27,0.39,-6000.0,4.0,NaN,0.05,NaN,NaN,NaN,0.10,1500.0,450.0,15000.0,176.35,183.15,15000.0,NaN,165.05,NaN,NaN,NaN,10500.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,1500.0,460.0,18000.0,185.40,193.10,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,1500.0,470.0,15000.0,196.90,203.25,15000.0,NaN,90.00,NaN,NaN,NaN,6000.0
30,0.01,NaN,NaN,NaN,0.45,NaN,1500.0,0.05,0.45,3000.0,480.0,15000.0,206.85,213.10,15000.0,NaN,192.50,NaN,NaN,NaN,1500.0
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,1500.0,490.0,18000.0,215.35,223.30,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
32,0.30,-1500.0,1.0,235.25,0.05,NaN,NaN,NaN,0.05,4500.0,500.0,18000.0,225.30,232.00,6000.0,-23.00,224.00,NaN,1.0,-1500.0,6000.0
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,1500.0,510.0,18000.0,235.35,243.15,15000.0,NaN,217.95,NaN,NaN,NaN,3000.0
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.00,1500.0,520.0,18000.0,245.25,253.15,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,530.0,16500.0,257.00,260.80,6000.0,-1.00,257.00,NaN,1.0,-1500.0,1500.0
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,540.0,18000.0,265.30,273.20,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,550.0,18000.0,275.25,283.15,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,560.0,15000.0,286.70,293.15,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,570.0,15000.0,296.65,303.15,15000.0,NaN,301.00,NaN,NaN,NaN,1500.0
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,580.0,18000.0,305.15,313.15,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,590.0,18000.0,315.10,323.15,15000.0,NaN,NaN,NaN,NaN,NaN,NaN
42,50.00,NaN,8130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3892.0,NaN,4087500.0